# Generated by Django 5.0.6 on 2024-06-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
