# Generated by Django 5.0.6 on 2024-06-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.blogsmodel'),
        ),
    ]
